### ISSUE TITLE
如何刷新

### ISSUE THREAD

**Issue by huangd-d** [everest-architecture/front-end-daily-question#26]
我公司的电脑是不关机的，入职 开机， 离职删库跑路。我这边看卡在277 几天了。 不知道是不是没更新 还是说 我电脑没关机没触发更新。 所以期望一个主动触发 功能，来让我心里有个底。

**Comment by zhangrenyang** [comment]
刷新按钮在这里
![Uploading 微信图片_20210825181708.png…]()

**Comment by zhangrenyang** [comment]
刷新功能在这里
![22](https://upload-markdown-images.oss-cn-beijing.aliyuncs.com/wei_xin_tu_pian_20210825181708_1629886782136.png)
